name: shego
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.1
  get: ^4.6.6
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  get_it: ^7.6.4
  shimmer: ^3.0.0
  flutter_riverpod: ^2.4.9
  connectivity_plus: ^5.0.2

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

